version: '3'

services:
#  app:
#    image: 'vr:latest'
#    build:
#      context: .
#    container_name: app
#    depends_on:
#     - db
#    environment:
#        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/vrsoftware
#        - SPRING_DATASOURCE_USERNAME=frodobolseiro
#        - SPRING_DATASOURCE_PASSWORD=frodobolseiro
#        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#    ports:
#      - "8081:8080"


  db:
    image: 'postgres:13.1-alpine'
    environment:
      - "POSTGRES_USER=frodobolseiro"
      - "POSTGRES_PASSWORD=frodobolseiro"
      - "POSTGRES_DB=vrsoftware"
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:


